#include "Generuoti_failai_class.h"
#include "Studentas_klase.h"
#include "palyginimas_class.h"

#include <fstream>
#include <sstream>
#include <iomanip>
#include <chrono>
#include <algorithm>
#include <numeric>
#include <iostream>

using std::vector;
using std::string;
using std::ifstream;
using std::ofstream;
using std::stringstream;
using std::cout;
using std::endl;
using std::setw;
using std::left;
using std::right;
using std::fixed;
using std::setprecision;
using std::to_string;
using std::chrono::high_resolution_clock;
using std::chrono::duration;
using std::sort;
using std::getline;
